Hooks:PostHook(TweakData, "_setup_scene_poses", "MorePosesInit", function(self)
self.scene_poses.weapon.nothing = {
	"husk1",
	"husk2",
	"husk3",
	"husk4",
	"husk_akimbo1",
	"husk_akimbo2",
	"husk_akimbo_x54",
	"husk_bow1",
	"husk_bow2",
	"husk_bullpup",
	"husk_card1",
	"husk_card2",
	"husk_card3",
	"husk_card4",
	"husk_generic1",
	"husk_generic2",
	"husk_generic3",
	"husk_generic4",
	"husk_generic5",
	"husk_generic6",
	"husk_infamous1",
	"husk_infamous2",
	"husk_infamous3",
	"husk_infamous4",
	"husk_lmg",
	"husk_m249",
	"husk_mg42",
	"husk_m95",
	"husk_minigun",
	"husk_mosconi",
	"husk_pistol1",
	"husk_r93",
	"husk_ray",
	"husk_rifle1",
	"husk_rifle2",
	"husk_rifle3",
	"husk_rifle4",
	"husk_rifle5",
	"husk_saw1",
	"husk_shotgun1",
	"generic_stance",
	"calibrate",
	required_pose = true
}
-- local weapons = {
	-- "amcar",
	-- "s552",
	-- "scar",
	-- "corgi",
	-- "ak74",
	-- "new_m4",
	-- "aug",
	-- "groza",
	-- "sub2000",
	-- "akm",
	-- "g36",
	-- "flint",
	-- "akm_gold",
	-- "tecci",
	-- "l85a2",
	-- "ching",
	-- "new_m14",
 	-- "famas",
	-- "vhs",
	-- "asval",
	-- "ak5",
	-- "galil",
	-- "komodo",
	-- "m16",
	-- "shak12",
	-- "contraband",
	-- "fal",
	-- "tkb",
	-- "g3",
	-- "spas12",
	-- "boot",
	-- "r870",
	-- "m590",
	-- "sko12",
	-- "benelli",
	-- "ksg",
	-- "saiga",
	-- "m1897",
	-- "huntsman",
	-- "b682",
	-- "aa12",
	-- "rpk",
	-- "par",
	-- "m60",
	-- "hk51b",
	-- "m249",
	-- "hcar",
	-- "mg42",
	-- "shuno",
	-- "hk21",
	-- "hailstorm",
	-- "msr",
	-- "r700",
	-- "sbl",
	-- "qbu88",
	-- "model70",
	-- "wa2000",
	-- "desertfox",
	-- "tti",
	-- "r93",
	-- "winchester1874",
	-- "siltstone",
	-- "mosin",
	-- "m95",
	-- "x_shrew",
	-- "x_usp",
	-- "x_breech",
	-- "x_sparrow",
	-- "x_hs2000",
	-- "x_p226",
	-- "x_packrat",
	-- "x_model3",
	-- "x_b92fs",
	-- "x_m1911",
	-- "x_2006m",
	-- "x_rage",
	-- "jowi",
	-- "x_g17",
	-- "x_maxim9",
	-- "x_chinchilla",
	-- "x_g22c",
	-- "x_legacy",
	-- "x_beer",
	-- "x_czech",
	-- "x_stech",
	-- "x_holt",
	-- "x_type54",
	-- "x_ppk",
	-- "x_g18c",
	-- "x_c96",
	-- "x_1911",
	-- "x_pl14",
	-- "x_deagle",
	-- "x_korth",
	-- "x_akmsu",
	-- "x_m45",
	-- "x_mp5",
	-- "x_mp7",
	-- "x_sr2",
	-- "x_hajk",
	-- "x_mac10",
	-- "x_cobray",
	-- "x_m1928",
	-- "x_pm9",
	-- "x_scorpion",
	-- "x_baka",
	-- "x_mp9",
	-- "x_olympic",
	-- "x_schakal",
	-- "x_shepheard",
	-- "x_vityaz",
	-- "x_erma",
	-- "x_tec9",
	-- "x_p90",
	-- "x_polymer",
	-- "x_coal",
	-- "x_sterling",
	-- "x_uzi",
	-- "x_sko12",
	-- "x_rota",
	-- "x_judge",
	-- "x_basset",
	-- "m32", 
	-- "gre_m79",
	-- "flamethrower_mk2",
	-- "saw",
	-- "drill",
	-- "ecp",
	-- "frankish",
	-- "arblast",
	-- "long",
	-- "elastic",
	-- "plainsrider"
-- }
table.insert(self.scene_poses.weapon.akimbo, "husk_akimbo_x54")
table.insert(self.scene_poses.weapon.akimbo, "husk_rifle1")
table.insert(self.scene_poses.weapon.akimbo, "husk_rifle2")
table.insert(self.scene_poses.weapon.akimbo, "husk_rifle4")
table.insert(self.scene_poses.weapon.akimbo, "husk_rifle5")
table.insert(self.scene_poses.weapon.akimbo, "husk_pistol1")
table.insert(self.scene_poses.weapon.akimbo, "husk_mosconi")
table.insert(self.scene_poses.weapon.akimbo, "husk_generic1")
table.insert(self.scene_poses.weapon.akimbo, "husk_generic2")
table.insert(self.scene_poses.weapon.akimbo, "husk_generic3")
table.insert(self.scene_poses.weapon.akimbo, "husk_generic4")
-- KSP pose
local wpn_pose_m249 = {
	"s552",
	"amcar",
	"akm",
	"ak74",
	"akm_gold",
	"new_m4",
	"m16",
	"scar",
	"ak5",
	"galil",
	"asval",
	"ching",
	"g36",
	"new_m14",
	"sub2000",
	"flint",
	"b682",
	"saiga",
	"benelli",
	"tti",
	"x_akmsu",
	"x_mp5",
	"x_basset",
	"akmsu",
	"mp5",
	"basset",
	"rpk",
	"hk21",
	"tkb",
	"spas12",
	"r870",
	"m1897",
	"m590",
	"m60",
	"hcar",
	"desertfox",
	"qbu88",
	"x_vityaz",
	"hk51b",
	"x_sterling"
}
for i, wpid in ipairs(wpn_pose_m249) do
	self.scene_poses.weapon[wpid] = self.scene_poses.weapon[wpid] or {} 
	table.insert(self.scene_poses.weapon[wpid], "husk_m249")
end
-- Thanatos pose
local wpn_pose_m95 = {
	"akm",
	"ak74",
	"akm_gold",
	"amcar",
	"new_m4",
	"m16",
	"g36",
	"ching",
	"new_m14",
	"ak5",
	"s552",
	"scar",
	"galil",
	"fal",
	"g3",
	"flint",
	"huntsman",
	"saiga",
	"ksg",
	"aa12",
	"tti",
	"rpk",
	"hk21",
	"mg42",
	"m249",
	"par",
	"m590",
	"sko12",
	"hk51b",
	"hcar",
	"tkb",
	"msr",
	"qbu88",
	"desertfox",
	"siltstone",
	"x_akmsu",
	"x_vityaz",
	"x_sterling",
	"x_basset",
	"x_sko12"
}
for i, wpid in ipairs(wpn_pose_m95) do
	self.scene_poses.weapon[wpid] = self.scene_poses.weapon[wpid] or {} 
	table.insert(self.scene_poses.weapon[wpid], "husk_m95")
end
-- Shotgun pose
local wpn_pose_sg = {
	"akm",
	"ak74",
	"akm_gold",
	"amcar",
	"new_m4",
	"m16",
	"g36",
	"ching",
	"new_m14",
	"ak5",
	"s552",
	"scar",
	"galil",
	"fal",
	"g3",
	"contraband",
	"flint",
	"huntsman",
	"saiga",
	"ksg",
	"aa12",
	"tti",
	"rpk",
	"hk21",
	"mg42",
	"m249",
	"par",
	"m32",
	"spas12",
	"benelli",
	"r870",
	"m590",
	"boot",
	"sko12",
	"m1897",
	"b682",
	"m60",
	"hk51b",
	"hcar",
	"msr",
	"r700",
	"qbu88",
	"siltstone",
	"x_akmsu",
	"winchester1874",
	"sbl",
	"ecp",
	"x_vityaz",
	"x_sterling",
	"x_sko12"
}
for i, wpid in ipairs(wpn_pose_sg) do
	self.scene_poses.weapon[wpid] = self.scene_poses.weapon[wpid] or {}
	table.insert(self.scene_poses.weapon[wpid], "husk_shotgun1")
end
-- LMG pose
local wpn_pose_lmg = {
	"ching",
	"fal",
	"g3",
	"x_erma",
	"x_sterling",
	"huntsman",
	"rpk",
	"hk21",
	"mg42",
	"m249",
	"par",
	"sko12",
	"b682",
	"m60",
	"hcar",
	"msr",
	"tti",
	"m95",
	"siltstone",
	"x_sko12"
}
for i, wpid in ipairs(wpn_pose_lmg) do
	self.scene_poses.weapon[wpid] = self.scene_poses.weapon[wpid] or {}
	table.insert(self.scene_poses.weapon[wpid], "husk_lmg")
end
-- MG42 pose
local wpn_pose_mg42 = {
	"famas",
	"x_erma",
	"huntsman",
	"par",
	"m60",
	"spas12",
	"benelli",
	"r870",
	"m95",
	"qbu88",
	"desertfox",
	"flamethrower_mk2"
}
for i, wpid in ipairs(wpn_pose_mg42) do
	self.scene_poses.weapon[wpid] = self.scene_poses.weapon[wpid] or {}
	table.insert(self.scene_poses.weapon[wpid], "husk_mg42")
end
-- saw pose
local wpn_pose_saw1 = {
	"amcar",
	"s552",
	"scar",
	"corgi",
	"ak74",
	"new_m4",
	"sub2000",
	"akm",
	"g36",
	"flint",
	"akm_gold",
	"tecci",
	"ching",
	"new_m14",
	"asval",
	"ak5",
	"galil",
	"m16",
	"shak12",
	"contraband",
	"fal",
	"g3",
	"ksg",
	"huntsman",
	"b682",
	"aa12",
	"rpk",
	"m60",
	"hk51b",
	"m249",
	"mg42",
	"hk21",
	"msr",
	"sbl",
	"model70",
	"tti",
	"r93",
	"winchester1874",
	"siltstone",
	"mosin",
	"x_akmsu",
	"x_m45",
	"x_mp5",
	"x_mp7",
	"x_sr2",
	"x_hajk",
	"x_mac10",
	"x_cobray",
	"x_m1928",
	"x_pm9",
	"x_scorpion",
	"x_baka",
	"x_mp9",
	"x_olympic",
	"x_schakal",
	"x_shepheard",
	"x_vityaz",
	"x_erma",
	"x_tec9",
	"x_polymer",
	"x_coal",
	"x_sterling",
	"x_uzi",
	"m32",
	"gre_m79"
}
for i, wpid in ipairs(wpn_pose_saw1) do
	self.scene_poses.weapon[wpid] = self.scene_poses.weapon[wpid] or {}
	table.insert(self.scene_poses.weapon[wpid], "husk_saw1")
end
-- akimbo2 pose
local wpn_pose_ak2 = {
	"amcar",
	"s552",
	"scar",
	"corgi",
	"ak74",
	"new_m4",
	"aug",
	"groza",
	"sub2000",
	"akm",
	"g36",
	"flint",
	"akm_gold",
	"tecci",
	"l85a2",
	"ching",
	"new_m14",
 	"famas",
	"vhs",
	"asval",
	"ak5",
	"galil",
	"komodo",
	"m16",
	"shak12",
	"contraband",
	"fal",
	"tkb",
	"g3",
	"spas12",
	"sko12",
	"benelli",
	"ksg",
	"saiga",
	"aa12",
	"hk51b",
	"hcar",
	"msr",
	"sbl",
	"qbu88",
	"model70",
	"wa2000",
	"desertfox",
	"tti",
	"r93",
	"siltstone",
	"m95",
	"ecp",
	"m32",
	"flamethrower_mk2",
	"hailstorm"
}
for i, wpid in ipairs(wpn_pose_ak2) do
	self.scene_poses.weapon[wpid] = self.scene_poses.weapon[wpid] or {}
	table.insert(self.scene_poses.weapon[wpid], "husk_akimbo2")
end
-- akimbo1 pose
local wpn_pose_ak1 = {
	"sub2000",
	"l85a2",
	"new_m14",
	"komodo",
	"spas12",
	"m1897",
	"huntsman",
	"b682",
	"flamethrower_mk2",
	"gre_m79",
	"drill",
	"long",
	"elastic",
	"plainsrider"
}
for i, wpid in ipairs(wpn_pose_ak1) do
	self.scene_poses.weapon[wpid] = self.scene_poses.weapon[wpid] or {}
	table.insert(self.scene_poses.weapon[wpid], "husk_akimbo1")
end
-- mosconi pose
local wpn_pose_mos = {
	"g36",
	"ching",
	"fal",
	"sko12",
	"huntsman",
	"b682",
	"aa12",
	"hcar",
	"mg42",
	"r93",
	"siltstone",
	"m95",
	"x_schakal",
	"x_sterling",
	"saw",
	"ecp",
	"flamethrower_mk2",
	"drill"
}
for i, wpid in ipairs(wpn_pose_mos) do
	self.scene_poses.weapon[wpid] = self.scene_poses.weapon[wpid] or {}
	table.insert(self.scene_poses.weapon[wpid], "husk_mosconi")
end
-- R93 pose
local wpn_pose_r93 = {
	"m249",
	"x_coal",
	"frankish",
	"arblast"
}
for i, wpid in ipairs(wpn_pose_r93) do
	self.scene_poses.weapon[wpid] = self.scene_poses.weapon[wpid] or {}
	table.insert(self.scene_poses.weapon[wpid], "husk_r93")
end
-- Pistol pose
local wpn_pose_pis = {
	"amcar",
	"s552",
	"scar",
	"ak74",
	"new_m4",
	"groza",
	"sub2000",
	"akm",
	"g36",
	"flint",
	"akm_gold",
	"tecci",
	"l85a2",
	"new_m14",
 	"famas",
	"vhs",
	"asval",
	"ak5",
	"galil",
	"komodo",
	"m16",
	"contraband",
	"fal",
	"tkb",
	"g3",
	"spas12",
	"r870",
	"m590",
	"sko12",
	"benelli",
	"ksg",
	"saiga",
	"aa12",
	"rpk",
	"par",
	"hk51b",
	"m249",
	"hcar",
	"mg42",
	"hk21",
	"msr",
	"qbu88",
	"wa2000",
	"desertfox",
	"tti",
	"r93",
	"siltstone",
	"m95",
	"x_akmsu",
	"x_mp5",
	"x_mp7",
	"x_sr2",
	"x_hajk",
	"x_mac10",
	"x_m1928",
	"x_pm9",
	"x_scorpion",
	"x_mp9",
	"x_olympic",
	"x_schakal",
	"x_shepheard",
	"x_vityaz",
	"x_erma",
	"x_tec9",
	"x_coal",
	"x_sterling",
	"x_uzi",
	"x_sko12",
	"x_rota",
	"x_basset",
	"x_judge",
	"ecp",
	"m32", 
	"flamethrower_mk2",
	"drill"
}
for i, wpid in ipairs(wpn_pose_pis) do
	self.scene_poses.weapon[wpid] = self.scene_poses.weapon[wpid] or {}
	table.insert(self.scene_poses.weapon[wpid], "husk_pistol1")
end
-- rifle5 pose
local wpn_pose_ri5 = {
	"corgi",
	"aug",
	"new_m14",
	"vhs",
	"g3",
	"spas12",
	"ksg",
	"saiga",
	"rpk",
	"par",
	"m60",
	"hk51b",
	"m249",
	"hcar",
	"hk21",
	"sbl",
	"qbu88",
	"wa2000",
	"desertfox",
	"tti",
	"x_mp5",
	"x_hajk",
	"x_olympic",
	"x_schakal",
	"x_shepheard",
	"x_erma",
	"x_tec9",
	"x_p90",
	"x_coal",
	"x_sterling",
	"saw",
	"ecp",
	"m32", 
	"flamethrower_mk2",
	"hailstorm",
	"drill",
	"long",
	"elastic",
	"plainsrider"
}
for i, wpid in ipairs(wpn_pose_ri5) do
	self.scene_poses.weapon[wpid] = self.scene_poses.weapon[wpid] or {}
	table.insert(self.scene_poses.weapon[wpid], "husk_rifle5")
end
-- rifle3 pose
local wpn_pose_ri3 = {
	"amcar",
	"s552",
	"scar",
	"ak74",
	"new_m4",
	"aug",
	"groza",
	"sub2000",
	"akm",
	"g36",
	"flint",
	"akm_gold",
	"tecci",
	"l85a2",
	"new_m14",
 	"famas",
	"vhs",
	"asval",
	"ak5",
	"galil",
	"komodo",
	"m16",
	"contraband",
	"fal",
	"spas12",
	"r870",
	"m590",
	"sko12",
	"benelli",
	"ksg",
	"saiga",
	"aa12",
	"rpk",
	"par",
	"m60",
	"hk51b",
	"m249",
	"hk21",
	"qbu88",
	"desertfox",
	"tti",
	"siltstone",
	"m95",
	"pistol",
	"x_akmsu",
	"x_m45",
	"x_hajk",
	"x_mac10",
	"x_m1928",
	"x_pm9",
	"x_scorpion",
	"x_baka",
	"x_olympic",
	"x_schakal",
	"x_shepheard",
	"x_tec9",
	"x_coal",
	"x_sterling",
	"x_uzi",
	"x_sko12",
	"x_basset",
	"x_judge",
	"saw",
	"ecp",
	"drill"
}
for i, wpid in ipairs(wpn_pose_ri3) do
	self.scene_poses.weapon[wpid] = self.scene_poses.weapon[wpid] or {}
	table.insert(self.scene_poses.weapon[wpid], "husk_rifle3")
end
-- rifle2 pose
local wpn_pose_ri2 = {
	"r870",
	"sko12",
	"saiga",
	"m1897",
	"aa12",
	"rpk",
	"par",
	"m249",
	"hcar",
	"mg42",
	"msr",
	"qbu88",
	"desertfox",
	"tti",
	"r93",
	"siltstone",
	"mosin",
	"m95",
	"x_shrew",
	"x_breech",
	"x_hs2000",
	"x_b92fs",
	"jowi",
	"x_maxim9",
	"x_chinchilla",
	"x_legacy",
	"x_beer",
	"x_holt",
	"x_type54",
	"x_ppk",
	"x_1911",
	"x_deagle",
	"x_akmsu",
	"x_mp5",
	"x_sr2",
	"x_hajk",
	"x_m1928",
	"x_pm9",
	"x_scorpion",
	"x_olympic",
	"x_schakal",
	"x_shepheard",
	"x_vityaz",
	"x_tec9",
	"x_polymer",
	"x_sterling",
	"x_sko12",
	"x_basset",
	"m32", 
	"flamethrower_mk2",
	"gre_m79",
	"saw",
	"drill",
	"ecp"
}
for i, wpid in ipairs(wpn_pose_ri2) do
	self.scene_poses.weapon[wpid] = self.scene_poses.weapon[wpid] or {}
	table.insert(self.scene_poses.weapon[wpid], "husk_rifle2")
end
-- rifle1 pose
local wpn_pose_ri1 = {
	"boot",
	"sko12",
	"saiga",
	"huntsman",
	"aa12",
	"par",
	"m249",
	"hcar",
	"mg42",
	"hk21",
	"msr",
	"tti",
	"r93",
	"m95",
	"x_maxim9",
	"x_chinchilla",
	"x_m1928",
	"x_olympic",
	"x_schakal",
	"x_shepheard",
	"x_vityaz",
	"x_polymer",
	"x_sterling",
	"x_sko12",
	"x_judge",
	"m32", 
	"ecp"
}
for i, wpid in ipairs(wpn_pose_ri1) do
	self.scene_poses.weapon[wpid] = self.scene_poses.weapon[wpid] or {}
	table.insert(self.scene_poses.weapon[wpid], "husk_rifle1")
end
-- bullpup pose
local wpn_pose_blp = {
	"amcar",
	"s552",
	"scar",
	"corgi",
	"ak74",
	"new_m4",
	"aug",
	"groza",
	"sub2000",
	"akm",
	"g36",
	"flint",
	"galil",
	"tkb",
	"huntsman",
	"hcar",
	"mg42",
	"shuno",
	"msr",
	"tti",
	"x_m45",
	"x_polymer",
	"m32", 
	"flamethrower_mk2",
	"drill",
	"ecp"
}
for i, wpid in ipairs(wpn_pose_blp) do
	self.scene_poses.weapon[wpid] = self.scene_poses.weapon[wpid] or {}
	table.insert(self.scene_poses.weapon[wpid], "husk_bullpup")
end
-- type54 pose
local wpn_pose_x54 = {
	"amcar",
	"s552",
	"scar",
	"ak74",
	"new_m4",
	"groza",
	"sub2000",
	"akm",
	"g36",
	"flint",
	"akm_gold",
	"tecci",
	"l85a2",
	"new_m14",
 	"famas",
	"vhs",
	"asval",
	"galil",
	"komodo",
	"m16",
	"contraband",
	"tkb",
	"g3",
	"spas12",
	"boot",
	"r870",
	"sko12",
	"ksg",
	"saiga",
	"aa12",
	"msr",
	"sbl",
	"qbu88",
	"wa2000",
	"desertfox",
	"tti",
	"r93",
	"siltstone",
	"m95",
	"x_shrew",
	"x_usp",
	"x_breech",
	"x_sparrow",
	"x_hs2000",
	"x_p226",
	"x_packrat",
	"x_b92fs",
	"x_m1911",
	"jowi",
	"x_g17",
	"x_maxim9",
	"x_g22c",
	"x_legacy",
	"x_beer",
	"x_czech",
	"x_stech",
	"x_holt",
	"x_type54",
	"x_ppk",
	"x_g18c",
	"x_c96",
	"x_1911",
	"x_pl14",
	"x_deagle",
	"x_korth",
	"x_mp7",
	"x_sr2",
	"x_mac10",
	"x_m1928",
	"x_pm9",
	"x_scorpion",
	"x_mp9",
	"x_schakal",
	"x_shepheard",
	"x_erma",
	"x_tec9",
	"x_uzi",
	"x_sko12",
	"x_rota",
	"x_judge",
	"x_basset",
	"flamethrower_mk2",
	"saw",
	"drill",
	"ecp"
}
for i, wpid in ipairs(wpn_pose_x54) do
	self.scene_poses.weapon[wpid] = self.scene_poses.weapon[wpid] or {}
	table.insert(self.scene_poses.weapon[wpid], "husk_akimbo_x54")
end
log("sause")
end)